# TODO! meld for our tests if I want to run everyting
# ie server combiners and reducers locally.
# Compose schema version
version: '3.4'

# Setup network
networks:
  default:
    name: fedn_default

services:
  # Client from FEDn repo
  client:
    environment:
      - GET_HOSTS_FROM=dns
      - FEDN_PACKAGE_EXTRACT_DIR=package
    build:
      context: .
      args:
        BASE_IMG: ${BASE_IMG:-python:3.10-slim}
    working_dir: /app
    volumes:
      - ${HOST_REPO_DIR:-.}/fedn:/app/fedn
    entrypoint: [ "sh", "-c" ]
    command:
      - "/venv/bin/pip install --no-cache-dir -e . && /venv/bin/fedn client start --init config/settings-client.yaml"
    deploy:
      replicas: 0
    depends_on:
      combiner:
        condition: service_healthy
