# syntax=docker/dockerfile:1

FROM ghcr.io/scaleoutsystems/fedn/fedn:0.16.1

RUN apt-get install -y wget && \
        wget -qO /bin/grpc_health_probe \
        https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.4.24/grpc_health_probe-linux-amd64 && \
        chmod +x /bin/grpc_health_probe && \
        apt-get remove -y wget && \
        apt autoremove -y

CMD ["/venv/bin/pip install --no-cache-dir -e . && /venv/bin/fedn controller start"]
